const SCHEDULER_STATUS_CHANNEL = 'SCHEDULER_STATUS_CHANNEL'
const ORI_PERSON_CHANNEL = 'ORI_PERSON_CHANNEL'
const ORI_ATTAINMENT_CHANNEL = 'ORI_ATTAINMENT_CHANNEL'
const ORI_STUDY_RIGHT_CHANNEL = 'ORI_STUDY_RIGHT_CHANNEL'
const KORI_COURSE_UNIT_CHANNEL = 'KORI_COURSE_UNIT_CHANNEL'
const KORI_COURSE_UNIT_REALISATION_CHANNEL = 'KORI_COURSE_UNIT_REALISATION_CHANNEL'
const KORI_STUDY_EVENT_CHANNEL = 'KORI_STUDY_EVENT_CHANNEL'
const KORI_LOCATION_CHANNEL = 'KORI_LOCATION_CHANNEL'
const KORI_ASSESSMENT_ITEM_CHANNEL = 'KORI_ASSESSMENT_ITEM_CHANNEL'
const KORI_EDUCATION_CHANNEL = 'KORI_EDUCATION_CHANNEL'
const KORI_MODULE_CHANNEL = 'KORI_MODULE_CHANNEL'
const KORI_ORGANISATION_CHANNEL = 'KORI_ORGANISATION_CHANNEL'
const ORI_TERM_REGISTRATION_CHANNEL = 'ORI_TERM_REGISTRATION'
const URN_STUDY_LEVEL_CHANNEL = 'URN_STUDY_LEVEL_CHANNEL'
const URN_COUNTRY_CHANNEL = 'URN_COUNTRY_CHANNEL'
const URN_EDUCATION_TYPE_CHANNEL = 'URN_EDUCATION_TYPE_CHANNEL'
const ORI_STUDY_RIGHT_PRIMALITY_CHANNEL = 'ORI_STUDY_RIGHT_PRIMALITY_CHANNEL'
const ILMO_ENROLMENT_CHANNEL = 'ILMO_ENROLMENT_CHANNEL'
const GRAPHQL_GRADE_SCALES_CHANNEL = 'GRAPHQL_GRADE_SCALES_CHANNEL'
const URN_DEGREE_TITLE_CHANNEL = 'URN_DEGREE_TITLE_CHANNEL'
const URN_EDUCATION_CLASSIFICATION_CHANNEL = 'URN_EDUCATION_CLASSIFICATION_CHANNEL'
const URN_STUDY_RIGHT_EXPIRATION_RULE_CHANNEL = 'URN_STUDY_RIGHT_EXPIRATION_RULE_CHANNEL'
const URN_ADMISSION_TYPE_CHANNEL = 'URN_ADMISSION_TYPE_CHANNEL'
const OSUVA_PLAN_CHANNEL = 'OSUVA_PLAN_CHANNEL'
const ORI_PERSON_GROUP_CHANNEL = 'ORI_PERSON_GROUP_CHANNEL'
const ORI_DISCLOSURE_CHANNEL = 'ORI_DISCLOSURE_CHANNEL'
const KORI_PUBLIC_CURRICULUM_PERIOD_CHANNEL = 'KORI_PUBLIC_CURRICULUM_PERIOD_CHANNEL'

module.exports = {
  SCHEDULER_STATUS_CHANNEL,
  ORI_PERSON_CHANNEL,
  ORI_ATTAINMENT_CHANNEL,
  ORI_STUDY_RIGHT_CHANNEL,
  KORI_COURSE_UNIT_CHANNEL,
  KORI_COURSE_UNIT_REALISATION_CHANNEL,
  KORI_STUDY_EVENT_CHANNEL,
  KORI_LOCATION_CHANNEL,
  KORI_ASSESSMENT_ITEM_CHANNEL,
  KORI_EDUCATION_CHANNEL,
  KORI_MODULE_CHANNEL,
  KORI_ORGANISATION_CHANNEL,
  ORI_TERM_REGISTRATION_CHANNEL,
  URN_STUDY_LEVEL_CHANNEL,
  URN_COUNTRY_CHANNEL,
  URN_EDUCATION_TYPE_CHANNEL,
  ORI_STUDY_RIGHT_PRIMALITY_CHANNEL,
  ILMO_ENROLMENT_CHANNEL,
  GRAPHQL_GRADE_SCALES_CHANNEL,
  URN_DEGREE_TITLE_CHANNEL,
  URN_EDUCATION_CLASSIFICATION_CHANNEL,
  URN_STUDY_RIGHT_EXPIRATION_RULE_CHANNEL,
  URN_ADMISSION_TYPE_CHANNEL,
  OSUVA_PLAN_CHANNEL,
  ORI_PERSON_GROUP_CHANNEL,
  ORI_DISCLOSURE_CHANNEL,
  KORI_PUBLIC_CURRICULUM_PERIOD_CHANNEL
}
