services:
  importer-db-staging-sampletaker:
    container_name: importer-db-staging-sampletaker
    build:
      context: .
      # Uncomment the following lines to run the application in development mode
      # command: [ "node", "--watch", "src/index.js" ]
      # volumes:
      # - .:/opt/app-root/src
    depends_on:
      - sis-importer-db
    environment:
      DATABASE_URL: postgres://postgres@sis-importer-db:5432/sis-importer-db

  sis-importer-db:
    container_name: sis-importer-sampletaker-db
    environment:
      POSTGRES_DB: sis-importer-db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:17.0
    volumes:
      - sis-importer-db-data:/var/lib/postgresql/data

  adminer:
    container_name: importer-db-staging-sampletaker-adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    image: adminer:4.8.1
    ports:
      - 5051:8080 # http://localhost:5051/?pgsql=sis-importer-db&username=postgres&db=sis-importer-db&ns=public

volumes:
  sis-importer-db-data:
