services:
    importer-api:
        command: "npm run start:dev"
        build:
            args:
                NODE_ENV: "development"
            context: importer-api
            dockerfile: dev.Dockerfile
        container_name: sis-importer-api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - importer-mankeli
        env_file:
            - importer-api/.env
        environment:
            DB_USERNAME: dev
            DB_PASSWORD: dev
            DB_PORT: 5432
            DB_HOST: importer-db
            DB_DATABASE: importer-db
            NATS_URI: nats://importer-nats:4222
            NATS_TOKEN: dev
            REDIS_URI: redis://importer-redis:6379
            SONIC: 1
            SERVICE_PROVIDER: fd
            ROOT_ORG_ID: ${ROOT_ORG_ID}
        ports:
            - 3002:3002 # explorer at http://localhost:3002/
        volumes:
            - ./importer-api:/opt/app-root/src

    importer-mankeli:
        deploy:
            replicas: 4
            mode: replicated
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            args:
                NODE_ENV: "development"
            context: importer-mankeli
            dockerfile: dev.Dockerfile
        command: "npm run start:dev"
        depends_on:
            - importer-db
            - importer-redis
            - importer-nats
        environment:
            DB_USERNAME: dev
            DB_PASSWORD: dev
            DB_PORT: 5432
            DB_HOST: importer-db
            DB_DATABASE: importer-db
            NATS_URI: nats://importer-nats:4222
            NATS_TOKEN: dev
            REDIS_URI: redis://importer-redis:6379
            SERVICE_PROVIDER: fd
        volumes:
            - ./importer-mankeli:/opt/app-root/src

    importer-db:
        container_name: sis-importer-db
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
            POSTGRES_DB: importer-db
        image: postgres:13.17
        ports:
            - 15234:5432
        volumes:
            - sis-importer-pgdata:/var/lib/postgresql/data

    importer-db-api:
        build:
            args:
                NODE_ENV: "development"
            context: importer-db-api
            dockerfile: dev.Dockerfile
        command: "npm run start:dev"
        container_name: sis-importer-db-api
        env_file:
            - importer-db-api/.env
        environment:
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_PORT: 5432
            DB_HOST: importer-db
            DB_DATABASE: importer-db
            REDIS_URI: redis://importer-redis:6379
            SERVICE_PROVIDER: fd
            IMPORTER_DB_API_USER: dev_user
            IMPORTER_DB_API_PASSWORD: dev_password
        ports:
            - 3005:3000
        volumes:
            - ./importer-db-api:/opt/app-root/src

    importer-redis:
        command: [ "redis-server", "--appendonly", "yes", "--port", "6379" ]
        container_name: sis-importer-redis
        image: redis:5.0.14
        ports:
            - 16379:6379
        volumes:
            - sis-importer-redis:/data

    importer-nats:
        command: -cid importer-nats -m 8222 --hb_fail_count 2 --hb_timeout 10s --hb_interval 10s --auth dev --file_slice_max_bytes 0 --file_slice_max_age 60s --max_msgs 5000 -store file -dir datastore
        container_name: sis-importer-nats
        image: nats-streaming:0.25.6
        ports:
            - 8223:8222 # Monitoring at http://localhost:8223/
        volumes:
            - sis-importer-datastore:/datastore

    importer-nats-streaming-console:
        container_name: sis-nats-streaming-console
        environment:
            - STAN_URL=nats://importer-nats:4222
            - STAN_MONITOR_URL=http://importer-nats:8222
        image: mozgoo/nats-streaming-console:latest
        ports:
            - 8282:8282 # http://localhost:8282/


volumes:
    sis-importer-redis:
    sis-importer-datastore:
    sis-importer-pgdata:

networks:
    default:
        name: importer_network
