services:
  importer-db:
    container_name: sis-importer-db
    image: registry-toska.ext.ocp-prod-0.k8s.it.helsinki.fi/sis-importer-db

  importer-db-api:
    build:
      args:
        NODE_ENV: "test"
      context: importer-db-api
    container_name: sis-importer-db-api
    tty: true
    depends_on:
      - importer-db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: importer-db
      DB_DATABASE: sis-importer-db
      NODE_ENV: test
      PORT: 3001
    ports:
      - 3001:3001
