#!/bin/bash
DIR_PATH=$(dirname "$0")
SERVICE=importer-redis
CONTAINER=sis-redis

read -p "Are you sure? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    ORDINAL_KEYS=(
    LATEST_ASSESSMENT_ORDINAL
    LATEST_ATTAINMENT_ORDINAL
    LATEST_COURSE_UNIT_ORDINAL
    LATEST_COURSE_UNIT_REALISATION_ORDINAL
    LATEST_EDUCATION_ORDINAL
    LATEST_MODULE_ORDINAL
    LATEST_ORGANISATION_ORDINAL
    LATEST_PERSON_ORDINAL
    LATEST_STUDY_RIGHT_ORDINAL
    LATEST_TERM_REGISTRATION_ORDINAL
    LATEST_STUDY_RIGHT_PRIMALITY_ORDINAL
    LATEST_ENROLMENT_ORDINAL
    GRAPHQL_GRADE_SCALES_CHANNEL
  )

  for key in "${ORDINAL_KEYS[@]}";
    do docker exec -t $CONTAINER redis-cli DEL $key &
  done
fi

wait
