name: 'Run tests'
description: 'Runs Cypress tests for service'

inputs:
  path:
    required: true
    description: 'Path to service folder'

runs:
  using: composite
  steps:
    - name: Install safe chain
      shell: bash
      run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      
    - name: Install packages
      shell: bash
      run: npm ci && npm ci --prefix ${{ inputs.path }}

    - name: Lint files
      shell: bash
      run: npm run eslint -- ${{ inputs.path }}

    - name: Run tests
      shell: bash
      run: npm test --prefix ${{ inputs.path }}
