name: importer-api

on:
  push:
    branches:
      - master
    paths:
      - importer-api/**
      - .github/workflows/importer-api-production.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          path: importer-api

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        uses: ./.github/actions/build-and-push-image
        with:
          image: importer-api
          tag: production
          password: ${{ secrets.QUAY_IO_TOKEN }}
