name: importer-db-api-production

on:
  release:
    types: [published]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run tests
  #       uses: ./.github/actions/run-tests
  #       with:
  #         path: importer-db-api

  build-and-push:
    runs-on: ubuntu-latest
    # needs: [test]

    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        uses: ./.github/actions/build-and-push-image
        with:
          image: importer-db-api
          tag: production
          password: ${{ secrets.QUAY_IO_TOKEN }}
