name: importer-mankeli

on:
  push:
    branches:
      - trunk
    paths:
      - importer-db-api/**
      - .github/workflows/importer-mankeli-staging.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          path: importer-mankeli

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        uses: ./.github/actions/build-and-push-image
        with:
          image: importer-mankeli
          tag: staging
          password: ${{ secrets.QUAY_IO_TOKEN }}
