name: importer-db-api-staging

on:
  push:
    branches:
      - master
    paths:
      - importer-db-api/**
      - .github/workflows/importer-db-api-staging.yaml

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run tests
  #       uses: ./.github/actions/run-tests
  #       with:
  #         path: importer-db-api
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci && npm ci --prefix importer-db-api
      - name: Lint files
        run: npm run eslint -- importer-db-api

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        uses: ./.github/actions/build-and-push-image
        with:
          image: importer-db-api
          tag: staging
          password: ${{ secrets.QUAY_IO_TOKEN }}
